-- AlterTable
ALTER TABLE `cliente` ADD COLUMN `bairro` VARCHAR(191) NULL,
    ADD COLUMN `cep` VARCHAR(191) NULL,
    ADD COLUMN `endereco` VARCHAR(191) NULL,
    ADD COLUMN `estado` VARCHAR(191) NULL,
    ADD COLUMN `numero` VARCHAR(191) NULL,
    ADD COLUMN `rg` VARCHAR(191) NULL,
    ADD COLUMN `telefone2` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `veiculo` ADD COLUMN `anoModelo` INTEGER NULL,
    ADD COLUMN `possuiChaveReserva` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `possuiManual` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `renavam` VARCHAR(191) NULL;
